[T-12] Edit Account Details
AryamanDubey28/seg_coursework_app pull request #11
Opened 2023-02-28 18:33 UTC by absirgue

Hello reviewers,

I hope you're having a great day!

Here is my PR for the edit account page.

It includes:
- the page itself
- edits of the auth.dart class to accomodate that change
- Unit and Widget tests for this task (the model used for testing - especially widget testing- can now be reused for other tasks as it allows to test any page without worrying about the navigation that used to bother us)

In the process, I also edited a few rules so them and their tests are also on this branch.

Let me know what you think, happy to make any change required and answer to any review !

Thanks,

2023-03-01 20:41 UTC, skellyhoe requested changes
Nice work!!

Here's some comments to consider:

- Write general comments for the loading indicator explaining where it's used and what it does.
- Write general comments on the edit_account page and write some comments for the methods used.
- Split the "Edit your email" and "Edit your password" in the edit_account page and make them 2 widgets to be called from the edit_account page.
- Add some padding to the texts and buttons in the edit_account page to make the look cleaner.
- Remove commented out code highlighted below.

2023-03-01 20:41 UTC, skellyhoe commented on test/screens/admin/edit_account_test.dart
> +      // expect(find.byKey(const ValueKey("edit_email_field")), findsWidgets);
remove commented out code

2023-03-01 20:46 UTC, skellyhoe commented on lib/pages/authenticate/edit_account.dart
> +                                  foregroundColor: Colors.white,
remove every hard coded color for the buttons

2023-03-02 14:52 UTC, skellyhoe requested changes
All good. Just remove the hard coded colors and it'll be perfect.

2023-03-02 14:52 UTC, skellyhoe commented on lib/widgets/edit_password_section.dart
> +                  foregroundColor: Colors.white,
hard coded color

2023-03-02 14:52 UTC, skellyhoe commented on lib/widgets/edit_password_section.dart
> +                  backgroundColor: Colors.teal[400],
hard coded color

2023-03-02 14:52 UTC, skellyhoe commented on lib/widgets/edit_email_section.dart
> +                            foregroundColor: Colors.white,
hard coded color

2023-03-02 14:52 UTC, skellyhoe commented on lib/widgets/edit_email_section.dart
> +                            backgroundColor: Colors.teal[400],
hard coded color

2023-03-02 14:53 UTC, skellyhoe commented on lib/pages/authenticate/edit_account.dart
> +      backgroundColor: Colors.grey[200],
hard coded color

2023-03-02 19:54 UTC, skellyhoe approved these changes
Thank you habibi.

2023-03-02 23:34 UTC, Ali-Alkhars requested changes
Great work habibi!

Please do the following:
- Add missing comments pointed out below
- Show a more accurate error message for when changing the email to a pre-existing email

2023-03-02 23:34 UTC, Ali-Alkhars commented on lib/pages/authenticate/edit_account.dart
> +class EditAccountPageState extends State<EditAccountPage> {
Add a general comment here explaining the functionality of this class

2023-03-02 23:34 UTC, Ali-Alkhars commented on lib/services/auth.dart
> +class Auth {
General comment here too

2023-03-03 08:47 UTC, AryamanDubey28 approved these changes
Great work on the rules, testing and Edit account UI!

Just get those integration tests passing and alls good

2023-03-04 14:51 UTC, Ali-Alkhars approved these changes
Well done! Thanks for making the requested changes

2023-03-04 21:08 UTC, merged