Child logout
AryamanDubey28/seg_coursework_app pull request #12
Opened 2023-03-01 09:00 UTC by AryamanDubey28

Hi Guys,

This is the implementation of the child mode log out task. Log out button in child mode is clicked and then they have to enter the PIN to actually log out back to the admin home

Let me know if there's any issues!

Thanks,
Aryaman

2023-03-01 21:42 UTC, skellyhoe requested changes
Good work!

Some notes:

- Remove commented out code highlighted.
- Write general comments on methods and pages you created.
- Remove print statement highlighted.
- Use pushAndReplace instead of push where highlighted.
- You wrote code in child_board_interface, but that file will be deleted. Make sure if the code is needed to add it somewhere else.

For the log out button consider these changes:
- When the admin presses the activate child view for the first time it should ask the admin for a PIN and then it saves it and doesn't ask for it again.
- It's still set to a tap gesture and not a hold and swipe gesture.
- Instead of a whole keyboard, the user should be presented with a number pad. 
- Instead of a whole text box, the user should be presented with a simple dialog as explained on WhatsApp.

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/admin/admin_interface.dart
> +      // routes: {
delete commented out code

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/child_board/child_board_interface.dart
> +        'adminScreen': (context) => AdminChoiceBoards(),
this whole file will be deleted make sure it has nothing important

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/child_menu/customizable_column.dart
> +      //Navigator.popAndPushNamed(context, 'adminScreen');
remove commented out code

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/child_menu/customizable_column.dart
> +      Navigator.push(
use pushAndReplace instead of push

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/child_menu/customizable_column.dart
> +                //   openLogoutDialog(context);
commented out code

2023-03-01 21:42 UTC, skellyhoe commented on lib/widgets/logout_alert_dialog.dart
> +
what does this widget do?

2023-03-01 21:42 UTC, skellyhoe commented on lib/pages/child_menu/customizable_column.dart
> +      print("navigating back to admin home");
remove print statement

2023-03-05 18:43 UTC, Ali-Alkhars requested changes
Hello, nice work overall!

I have some minor comments you could see below. 

**Other than that I have one comment,** I know that integration tests are cool and everything, but they're slow and kinda shi**y ngl haha. I don't really see a reason why you can't do the same tests as widget tests

2023-03-05 18:43 UTC, Ali-Alkhars commented on lib/main.dart
> +      //home: Wrapper(),
Remove commented out code

2023-03-05 18:43 UTC, Ali-Alkhars commented on lib/pages/admin/admin_side_menu.dart
> +              // onTap: () => Navigator.of(context).pushReplacement(MaterialPageRoute(
Remove commented out code

2023-03-05 18:43 UTC, Ali-Alkhars commented on lib/pages/authenticate/wrapper.dart
> +            //return const AdminInterface();
Remove commented out code

2023-03-05 18:43 UTC, Ali-Alkhars commented on lib/pages/child_menu/customizable_column.dart
> +    if (pin_controller.text.trim() == "0000") {
Why is the password hardcoded?

2023-03-05 18:43 UTC, Ali-Alkhars commented on lib/widgets/clickable_images_grid.dart
> +Future speak(String text) async {
Add a doc comment explaining what the method does

2023-03-08 10:53 UTC, AryamanDubey28 commented
Hi guys,
Apologies for the delays but I've incorporated all the changes so check them out when you can!

2023-03-08 21:21 UTC, skellyhoe approved these changes
Nice job!

I left some comments down. For the dialog widget, if it doesn't work then don't implement it. Make sure to pull from main to get the most up to date changes and see if they conflict with your work. I'll approve it now but make sure to delete the commented out code first. Also check with the others to see if we're still doing integration tests.

2023-03-08 21:21 UTC, skellyhoe commented on lib/widgets/edit_pin_section.dart
> +    //Navigator.of(context).pop();
commented out code

2023-03-08 21:21 UTC, skellyhoe commented on lib/widgets/edit_pin_section.dart
> +  void show_alert_dialog(String text) {
Duplicate method. Make it a separate widget if possible.

2023-03-08 21:21 UTC, skellyhoe commented on lib/main.dart
> +      //home: Wrapper(),
still commented out code here

2023-03-08 21:21 UTC, skellyhoe commented on lib/pages/admin/admin_side_menu.dart
> +  void show_alert_dialog(BuildContext context, String text) {
Duplicate method. Make it a separate widget if possible.

2023-03-10 18:11 UTC, Ali-Alkhars requested changes
- For some reason the themes don't work on the admin's side
- Users can enter a text pin from the edit account page and it gets accepted! (the keyboard should be only digits & it should show an error message if it was anything other than digits)
- Try clicking on the change pin text. The keyboard covers the text field.
- I wasn't asked to enter a pin. When I clicked on child app without setting a pin I was taken there and got stuck!

2023-03-10 18:23 UTC, absirgue requested changes
Hi Aryaman,

Thanks for the work. I like the hold button and the new edit account page.

First (as shown by screenshots attached), firebase errors are passed in to the prompt for the pin input field in the edit account page. This should abolsutely be avoided (show a different UI when my pin is not yet configured, will be way better + actually catch those errors and never display them to the user as raw as this).

Second, the custom theme feature fails on your branch. It works on main and everywhere else, please find the reason why it does not on ur branch (probably a failed merge conflict resolution) and correct it so that the custom themes are exactly working as they do on main (just copy main from main and do some of ur changes again if needed). 

Third, the testing does not cover enough cases (as illustrated by the fact that the other points of the reviews are coming up only in manual testing). Please test:
- pins longer than 4 digits
- pins that don't only contain numbers
- you can not navigate to child app if you didn't set a pin

Fourth, there is a significant UX problem: the admin can go in the child app before having even set a pin. This does not make much sense and should be avoided (show na alert dialog if you don't have set a pin yet and u try to go to the child app asking to first set a pin).

Five, you can put letters in your pin which 1- is not what we want. 2- you can not input letters in the numeric keyboard when trying to go from child app to admin app. Please change the keyboard for pin creation to be the same numeric keyboard

I know this is not the expected review as we were all hoping to be ready to merge this task. It is now 13 days late. Please integrate all of these changes ASAP and do manual testing on your own for a significant time before asking for reviews again. Your sprint 3 task is big and this task now needs to be done in a nice way. 
<img width="603" alt="Screen Shot 2023-03-10 at 6 07 05 PM" src="https://user-images.githubusercontent.com/94190429/224393995-eba643b5-cf02-40ba-8cc5-f99405f1908b.png">
<img width="610" alt="Screen Shot 2023-03-10 at 6 07 34 PM" src="https://user-images.githubusercontent.com/94190429/224393996-eddc7ef1-014c-4f21-b6d1-110aa665acff.png">

Thanks

2023-03-11 22:57 UTC, dmunipi1 approved these changes
Well done Aryaman

2023-03-12 15:17 UTC, merged