T16 item availability child
AryamanDubey28/seg_coursework_app pull request #13
Opened 2023-03-01 15:20 UTC by dmunipi1

Hello reader,

This task is to make items seem unavailable on the child side.
When an item is unavailable it should have a red X icon over it and it should be blurred, unavailable items are not clickable.
I have separated the unavailable icon and "look" into a widget called item_unavailable.
Other helpful code you will find in child_boards (in pages) and clickable_images_grid (in widgets).
The images currently displayed are temporary and for testing purposes, that includes the category title and image. That needs to be resolved when the loading categories and items task is finished, I will be happy to help with that if needed.
If you have any questions or comments please let me know.

Thanks, 
Dion

2023-03-01 21:05 UTC, skellyhoe requested changes
Good work! Clear and commented code!

I highlighted some issues that you should fix before merging into main.

However, for now, hard coded colors highlighted should be removed and the test highlighted should be refactored.

2023-03-01 21:05 UTC, skellyhoe commented on lib/main.dart
> +//   WidgetsFlutterBinding.ensureInitialized();
Make sure to return main as it was.

2023-03-01 21:05 UTC, skellyhoe commented on lib/pages/child_board/child_board.dart
> +            Navigator.of(context).pushReplacement(MaterialPageRoute(
Make sure when you pull from main to keep my changes (to pop the page instead of pushing a replacing page.)

2023-03-01 21:05 UTC, skellyhoe commented on lib/pages/child_board/child_board.dart
> +            color: Colors.teal, borderRadius: BorderRadius.circular(8)),
remove every hard coded color when you pull from main

2023-03-01 21:05 UTC, skellyhoe commented on lib/pages/child_board/child_board.dart
> +        splashColor: Colors.blue.shade900,
hard coded color

2023-03-01 21:05 UTC, skellyhoe commented on test/screens/child/child_board_test.dart
> +      'ChildBoards navigates back to the parent menu when the back button is pressed',
To do this test effectively

1. Start on customizable column and verify that customizable column is loaded.
2. Tap on a category. (Use pumpAndSettle() after this.)
3. Verify that the ChildBoards is loaded.
4. Tap the back button. (Use pumpAndSettle() after this.)
5. Verify that customizable column is loaded.

2023-03-01 21:05 UTC, skellyhoe commented on lib/pages/child_board/child_board.dart
> +          color: Color.fromARGB(255, 0, 76, 153),
hard coded color

2023-03-02 20:00 UTC, absirgue reviewed
Hello,

Thanks for the work!

In addition to Yousef's comments, can you try to make it easy for the person that will implement the fetching of the item data to transfer the data to this child_board page.

What I mean is that that person will have to get the data when the child "menu" is loaded and then when a category is clicked the data can just be based on to your class, doesn't have to be loaded again. In this regard, it would be nice to create a constructor for your class (or equivalent solution if you have a better idea) that takes the data of a category and its items and turn them into the now hardcoded categoryImage and images fields. 

For now this constructor can just set them to the hardcoded values you have here but at least the person that will implement this later task has an easy interface to work with.

Thanks!

2023-03-03 11:13 UTC, dmunipi1 commented
Hello guys, 

Thanks for your comments and suggestions.
I have removed all hard coded colours.
Made the page to pop not push and left other changes that were on the main branch when I pulled.
I commented out the test Yousef mentioned for now because it is giving me a http error, I think its because the temporary images and their https (what I understood from the errors), and I will uncomment later into development when we have database queries sorted and when we remove the temporary images.
As per Anton's comment, that was already completed but it was commented out so maybe you didn't notice, I've moved the comments up to make it easier for the person implementing.

Thanks

2023-03-03 16:43 UTC, skellyhoe approved these changes
Thank you! All good!

2023-03-05 17:43 UTC, Ali-Alkhars approved these changes
Nice and clean. Well done!

2023-03-05 20:36 UTC, merged