T 09 item backend
AryamanDubey28/seg_coursework_app pull request #14
Opened 2023-03-02 16:06 UTC by Ali-Alkhars

Hello everyone! T-09 (implementing the add, delete and edit buttons for choice board items) is done.

### These are the main things I added:
- add item widget
- edit item widget
- delete item alert dialogue
- A class for firebase manipulation functions (handling backend)
- Widget tests and Unit tests for all added classes
- Had to do lots of refactoring to make classes able to take mock firebase functions for testing

_**Note:**_ Manual testing is very tricky because loading data from the database is not yet implemented. If you would like to manually test:
- go to our firestore console 
- manually add three categories (with correct fields)
- Take the ids of these created categories
- Go to flutter: lib/data/choice_boards_data.dart
- Paste one id to each Draggable list (change the current data)
- Create items using the app (add an item) buttons
- Copy the ids of the items from the firestore console
- Paste them into the ids of the Draggable list items
- Now you should also be able to edit/delete items using the app buttons

2023-03-02 20:32 UTC, absirgue approved these changes
Awesome work sir, clean and very well tested.

Just this tiny comment to delete and it's perfect.

2023-03-02 20:32 UTC, absirgue commented on lib/widgets/hero_dialog_route.dart
> +  /// {@macro hero_dialog_route}
delete this comment

2023-03-03 14:38 UTC, Digital-Brendan approved these changes
Everything looks great - nicely designed and commented.

If I was being picky, I would give two particular functions more concise names, specifically `handleSavingItemToFirestore` and `handleEditingItemInFirestore`.

How about `saveItemToFirestore` or just `saveItem`?

Generally though, great code!

2023-03-03 16:05 UTC, AymenBerb requested changes
<img width="1512" alt="Screenshot 2023-03-03 at 16 03 14" src="https://user-images.githubusercontent.com/99401670/222768503-868acb31-3939-44aa-ab62-ab089f8da281.png">

Can you make item's name as a more recgnizable text field ? and maybe reduce the size of the pop up. (it doesnt need to take the whole screen (maybe add paading left and right))

2023-03-03 16:05 UTC, AymenBerb commented on lib/helpers/mock_firebase_authentication.dart
> +class MockFirebaseAuthentication extends Mock implements FirebaseAuth {}
What is this file for ?

2023-03-04 16:15 UTC, Ali-Alkhars commented on lib/helpers/mock_firebase_authentication.dart
> +class MockFirebaseAuthentication extends Mock implements FirebaseAuth {}
I need it to mock FirebaseAuthentication

2023-03-04 16:58 UTC, AymenBerb approved these changes
well done !

2023-03-05 17:14 UTC, merged