T19-Existing-Items
AryamanDubey28/seg_coursework_app pull request #23
Opened 2023-03-14 21:32 UTC by Digital-Brendan

Hi all,

For this ticket, I implemented:

- showing all created items to the user
- creating a categoryItem from an existing item
- deleting an item from an existing categoryItem
- deleting all instances of an item (all categoryItems created for it)
- making sure the user knows the consequences of deleting an item
- a new 'categoryItemExists' function.

Basically, to add an existing item to a category, the user can choose to see a list of already existing items and tap on the one they want to add. If it is already present in the category, no duplicate will be created. 

To delete an item, the user can select to 'Delete Everywhere' when tapping on the delete icon beside a categoryItem (this is the only way to truly delete an item). This deletes all categoryItems created for the item, the item's image, then the item itself, as well as updating the ranks of the other categoryItems within the affected categories. The user is warned of the consequences of this before continuing, with traffic-light-coloured buttons indicating severity of deletion.

To the best of my knowledge, I have tested each of these features thoroughly, but of course, if you think of anything else, let me know!

Thanks :)

2023-03-15 14:57 UTC, Digital-Brendan commented
**Update**: merge conflicts should have been resolved, and my code is now fully integrated with T20.

2023-03-15 17:28 UTC, Digital-Brendan commented
Also please note that although the number of line changes seems excessive, the majority of these are due to the automatic reformatting that occurs when saving a file.

2023-03-15 22:47 UTC, absirgue requested changes
Hey,

Thanks for the work!

First little comment, this is not your fault at all I fully understand but would be nice if you can try to remove your code format or something to have the code presented like it is for there rest of us bcs it looks really dense and compact now. (if you can't do it we can find a solution like I could go back and save the files myself for them to be formatted properly before merging but I'm not sure that would work and it's not ideal).

Apart from that, I think there are a few points that must be addressed:
- First, in terms of UI/UX, it is strange to have the widget to add an item look like that. The "create new item" and "use existing item" buttons should not be on the same level and the "use existing item" one should not be able to be seen only after entering a name and an image if you see what I mean. I believe there are 2 solutions for that:
                  1. put the "use existing item" button at the top of this widget and then have the whole section about if you want to create a new item (so the thing to select an image, the thing to enter a name, and the button "create new item" underneath). If that makes any sense.
                  2. make it so that when you add an item, it opens a widget that allows you to choose between using an existing one or creating a new one and redirects you to the page you built or to the widget Ali built depending on the choice.

=> I believe the first one is quite easy to do and may actually look the best. Please lmk if I didn't explain it clearly.

Second UI problem, Can you show the name of the items in addition to the image on the page where I can select which of the existing item I want to add? (makes it clear +_ if I have two pictures for the same item for some reason I can know which is which and which word will be read to the child).

Third, can you add a search bar to this page (it will get loaded with a lot of items)? Yousef did it in his branch I believe so you can check it out but I think it is core to keeping the functionality you just implemented usable.

And yep fourth thing. I love the way you implemented the deleting functionality I didn't notice it at first sight bcs wasn't expecting it to be implemented that way but it's great!! Only thing, once again just a small UX concern, can you make the "delete everywhere" button not stand out that much (less bright red) and make it the middle or leftmost button instead of the rightmost bcs I think as a user you have a tendency to just click on the red button that's the rightmost and that would be bad. On top of that, can you make just a small alert dialog that asks the user to confirm the deletion of ALL the item and category items only because it would be quite painful for them to do it accidentally.

Thanks, let me know if you have any questions :)

2023-03-19 22:19 UTC, absirgue approved these changes
Thanks for integrating all the requested changes. Looks perfect to me!

2023-03-20 00:11 UTC, Ali-Alkhars requested changes
Hey Brendan, really great work!

I added some comments below but they are all minor stuff to change, so should not take much time.

**There is also this little bug:** Adding a pre-existing item should take the current availability of the item, not become True on default.

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/widgets/existing_items_grid.dart
> +    DocumentSnapshot categoryItem = await widget.firestore.collection('categoryItems/${widget.categoryId}/items').doc(itemId).get();
move this to a new method in firebase_functions

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/pages/admin/add_existing_item.dart
> +        drawer: const AdminSideMenu(),
Would be better for UX if you change the menu drawer to a back button

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/pages/admin/add_existing_item.dart
> +          return CircularProgressIndicator();
Use the `custom_loading_indicator.dart` widget instead of this. It looks way better

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/pages/admin/add_choice_board_item.dart
> +                    Padding(padding: const EdgeInsets.fromLTRB(16, 16, 16, 8), child: Text("Already have an item in mind?"),),
Hardcode the text colour to black. In the begging, I had the text colour white and I didn't notice it.

Also, increase the text size? Maybe the same size as the "Pick an image" text if it looks good

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/widgets/existing_items_grid.dart
> +  final List<ImageDetails> imagesList;
move this to the top with the other fields

2023-03-20 00:11 UTC, Ali-Alkhars commented on lib/widgets/existing_items_grid.dart
> +      return Text("No items to show. Add some in the 'Choice Board' page");
Wrap this with a `Center` and increase the text size so it looks nicer

2023-03-20 00:41 UTC, Digital-Brendan commented on lib/widgets/existing_items_grid.dart
> +    DocumentSnapshot categoryItem = await widget.firestore.collection('categoryItems/${widget.categoryId}/items').doc(itemId).get();
I'm not sure how to do this since it needs the context of its parent widget? (where to redirect user and what snackbar message to display)

2023-03-20 00:59 UTC, Digital-Brendan commented on lib/pages/admin/add_existing_item.dart
> +        drawer: const AdminSideMenu(),
This is good though I like the idea of being able to use Android's native back button and still have access to the admin side menu without exiting the current page. I'm not sure which is a better UX?

2023-03-20 10:19 UTC, Ali-Alkhars commented on lib/widgets/existing_items_grid.dart
> +    DocumentSnapshot categoryItem = await widget.firestore.collection('categoryItems/${widget.categoryId}/items').doc(itemId).get();
I think you misunderstood me here. I meant move only `DocumentSnapshot categoryItem = await widget.firestore.collection('categoryItems/${widget.categoryId}/items').doc(itemId).get();` to `firebase_functions` and call it here

2023-03-20 10:29 UTC, Digital-Brendan commented on lib/widgets/existing_items_grid.dart
> +    DocumentSnapshot categoryItem = await widget.firestore.collection('categoryItems/${widget.categoryId}/items').doc(itemId).get();
Oh that makes much more sense

2023-03-20 11:04 UTC, Digital-Brendan commented
Hey @Ali-Alkhars that should be everything implemented! Thanks

2023-03-20 12:57 UTC, Ali-Alkhars commented on lib/pages/admin/add_existing_item.dart
> +        drawer: const AdminSideMenu(),
I see, but there’s no back button for ios, so I think it’s better to make a back button instead of a menu.

2023-03-21 02:49 UTC, skellyhoe commented
I tried to fix conflicts I think it should be good now. There's one test that fails and I think its because the delete item button isn't doing pushAndReplace with the current isMock boolean. It could also fail because of LoadingIndicator.show() and .dispose are being called in a test. To avoid this you should surround them with an if statement to not run when isMock is true.

2023-03-21 18:49 UTC, dmunipi1 approved these changes
Good job guys

2023-03-21 18:51 UTC, Ali-Alkhars approved these changes

2023-03-21 19:01 UTC, merged