T23 visual timetable backend
AryamanDubey28/seg_coursework_app pull request #25
Opened 2023-03-17 19:20 UTC by skellyhoe

Hello. This task is finally done.

Here's a summary of changes:

- Visual timetable is now linked with the database which means any item the user creates in the admin choice board will now be fetched automatically from the database.
- Any timetable the user saves will now be loaded from the database in the All saved timetables page.
- The user can now long press an item in the visual timetable page to cross it out.
- When clicking on a saved timetable, the user can now see an expanded version of it and tap on an item to cross it out.
- Deleting and adding a timetable is now linked with the database.
- The user can't add or delete a timetable if there's no connection.
- If there's no connection, all items that should be loaded from the database will be loaded from the cache.
- Refactored the look of the theme selection page.
- Refactored how visual timetable is built.

NOTE:
If any widget uses the isDeviceConnected field of the CheckConnection class, make sure to call CheckConnection.stopMonitoring() in the dispose() function of that widget. This is to prevent memory leaking.

Thank you.

2023-03-18 11:54 UTC, Ali-Alkhars requested changes
I think it works well, there are minor things to be changed though.

Also, I think you'll have to add tests for the models you created (I'm not sure). Check the test coverage.

2023-03-18 11:54 UTC, Ali-Alkhars commented on lib/helpers/cache_manager.dart
Would be better if you renamed `storeLibraryInCache` and `getLibraryFromCache` to more specific names because I'll later move choice boards cache methods to this file.

Also, add comments to the last two methods and a general comment for the CacheManager class.

2023-03-18 11:54 UTC, Ali-Alkhars commented on lib/models/list_of_timetables.dart
> +  ///Returns false if it's already saved. Saves the timetable and returns true if not.
This method has a void return type, but the comment suggests it's a boolean?

2023-03-18 11:54 UTC, Ali-Alkhars commented on lib/models/timetable.dart
Add comments

2023-03-18 11:54 UTC, Ali-Alkhars commented on lib/pages/admin/admin_choice_boards.dart
> +                    name: category.title, imageUrl: category.imageUrl, itemId: "hahalool"), //Delet. later
hahalool, Delet. later

2023-03-18 11:54 UTC, Ali-Alkhars commented on lib/pages/visual_timetable/visual_timetable.dart
> +    // TODO: implement initState
remove comment

2023-03-18 14:12 UTC, skellyhoe commented on lib/pages/admin/admin_choice_boards.dart
> +                    name: category.title, imageUrl: category.imageUrl, itemId: "hahalool"), //Delet. later
😂😂😂😂

2023-03-19 20:16 UTC, skellyhoe commented
> I think it works well, there are minor things to be changed though.
> 
> Also, I think you'll have to add tests for the models you created (I'm not sure). Check the test coverage.

I removed some functions in the models as I realized they were never used. I'll increase coverage on the rest.

2023-03-20 10:01 UTC, absirgue requested changes
Hey,

Thanks for the work.

I left an in-code comments and I have a few more things:
 1- can you make all the return AlertDialog(......) use my error_dialog_helper located in the helpers folder instead for code consistency and to avoid code duplication. Can you also delete the show_error_dialog widget just bcs we don't need two files doing the same thing (I know you didn't add it but I just now noticed it).
2- I am attaching screenshots of a lot of widget methods that are not tested. Can you please write tests for them (I know Ali did so you can checkout his work). 
3- then on the functionality side it's all really really nice. Congrats! Just two small things:
           - can you make it so that when I save a timetable I am redirected to the menu with all the saved time tables (like this I do realize that it was actually saved + I don't know that's what I though would happen with the UX of the little prompt to change the name and all but it didn't)
           - can you show the name of the items when I'm composing a timetable? Just bcs like some pictures could be a bit ambiguous maybe and bcs like this my eyes can scan the page for an image OR for the name but like I don't have to ask myself what the image means if I don't want to

Apart from these little things, perfect job. 
Thanks!

(I am also attaching a few screenshots of places where the test coverage isn't as good on top of the widget method). 

<img width="926" alt="Screen Shot 2023-03-20 at 9 48 36 AM" src="https://user-images.githubusercontent.com/94190429/226307093-fabb6436-5c44-48d3-b0b4-9d839597cae1.png">

<img width="859" alt="Screen Shot 2023-03-20 at 9 48 21 AM" src="https://user-images.githubusercontent.com/94190429/226307086-122ce867-07e0-4f9a-8017-e440aba41d43.png">

<img width="702" alt="Screen Shot 2023-03-20 at 9 48 29 AM" src="https://user-images.githubusercontent.com/94190429/226307090-97eb5b80-9d38-454c-b014-94f1b708f251.png">

<img width="981" alt="Screen Shot 2023-03-20 at 9 47 49 AM" src="https://user-images.githubusercontent.com/94190429/226307074-06c10188-fce2-491a-b081-0c76fa4713d0.png">
<img width="371" alt="Screen Shot 2023-03-20 at 9 48 12 AM" src="https://user-images.githubusercontent.com/94190429/226307083-21bab22f-c17e-44da-a2ef-eb910f32501a.png">
<img width="965" alt="Screen Shot 2023-03-20 at 9 49 46 AM" src="https://user-images.githubusercontent.com/94190429/226307085-3b5876c5-bee9-4485-9052-6f26f3b58f79.png">

2023-03-20 10:01 UTC, absirgue commented on lib/helpers/cache_manager.dart
> +import 'dart:convert';
Why did you need this file? from what I saw from Ali's branch he manages to manage the cache without it? If it's for refactoring did you make Ali's files use it ?

Also, it is not tested at all I think its coverage is close to 0%. Do you think you can do something abt it?

2023-03-20 16:45 UTC, skellyhoe commented
Thank you. Just did the non-test things. I'll push the test stuff soon.

2023-03-20 20:48 UTC, skellyhoe commented
> Hey,
> 
> Thanks for the work.
> 
> I left an in-code comments and I have a few more things: 1- can you make all the return AlertDialog(......) use my error_dialog_helper located in the helpers folder instead for code consistency and to avoid code duplication. Can you also delete the show_error_dialog widget just bcs we don't need two files doing the same thing (I know you didn't add it but I just now noticed it). 2- I am attaching screenshots of a lot of widget methods that are not tested. Can you please write tests for them (I know Ali did so you can checkout his work). 3- then on the functionality side it's all really really nice. Congrats! Just two small things: - can you make it so that when I save a timetable I am redirected to the menu with all the saved time tables (like this I do realize that it was actually saved + I don't know that's what I though would happen with the UX of the little prompt to change the name and all but it didn't) - can you show the name of the items when I'm composing a timetable? Just bcs like some pictures could be a bit ambiguous maybe and bcs like this my eyes can scan the page for an image OR for the name but like I don't have to ask myself what the image means if I don't want to
> 
> Apart from these little things, perfect job. Thanks!
> 
> (I am also attaching a few screenshots of places where the test coverage isn't as good on top of the widget method).
> 
> <img alt="Screen Shot 2023-03-20 at 9 48 36 AM" width="926" src="https://user-images.githubusercontent.com/94190429/226307093-fabb6436-5c44-48d3-b0b4-9d839597cae1.png">
> 
> <img alt="Screen Shot 2023-03-20 at 9 48 21 AM" width="859" src="https://user-images.githubusercontent.com/94190429/226307086-122ce867-07e0-4f9a-8017-e440aba41d43.png">
> 
> <img alt="Screen Shot 2023-03-20 at 9 48 29 AM" width="702" src="https://user-images.githubusercontent.com/94190429/226307090-97eb5b80-9d38-454c-b014-94f1b708f251.png">
> 
> <img alt="Screen Shot 2023-03-20 at 9 47 49 AM" width="981" src="https://user-images.githubusercontent.com/94190429/226307074-06c10188-fce2-491a-b081-0c76fa4713d0.png">
> 
> <img alt="Screen Shot 2023-03-20 at 9 48 12 AM" width="371" src="https://user-images.githubusercontent.com/94190429/226307083-21bab22f-c17e-44da-a2ef-eb910f32501a.png">
> 
> <img alt="Screen Shot 2023-03-20 at 9 49 46 AM" width="965" src="https://user-images.githubusercontent.com/94190429/226307085-3b5876c5-bee9-4485-9052-6f26f3b58f79.png">

Done 1, 2 (except cache stuff as we're not testing them yet), and 3 (the second point only). For the first point, even though the implementation is simple, I don't feel like it makes sense for the user to be forcefully redirected when they save a timetable.

2023-03-20 22:24 UTC, Ali-Alkhars approved these changes
Well done!

2023-03-21 09:45 UTC, absirgue approved these changes
Fantastic work! Congrats

2023-03-21 11:11 UTC, merged