T05 child menu UI
AryamanDubey28/seg_coursework_app pull request #6
Opened 2023-02-15 16:37 UTC by Digital-Brendan

I was tasked with creating a simple UI for the menu that presents categories to the child, and implement testing.

- Scrollable column of clickable categories
- Each row is responsive (new image previews can easily be added)
- Once connected to other views, clicking on a category/row will navigate user to it
- Future plans to add background colour customisation (Yousef's job?)

I struggled to think of what other tests would be useful considering, right now, the only thing that this card asked for was buttons - any additions welcome.

Thanks!

2023-02-15 16:40 UTC, Digital-Brendan commented
You may see that, for my first few commits, there's a discrepancy with the email I used (I changed to a new workstation and forgot to update `git config --global`). Hopefully this doesn't skew things too much on my TeamFeedback page.

2023-02-15 19:13 UTC, Digital-Brendan commented
Also you will be aware that I used FlutterFlow to create the simple design. Please know that I won't be using this in the future due to its unnecessarily cumbersome overhead - I apologise for this

2023-02-16 13:14 UTC, Ali-Alkhars requested changes
Hey, the UI looks pretty cool! Well done.

**However, I have the following questions/change requests:**
- The boxes now don't take an image. They are just white boxes. You should convert them to a card with an image as a child (so you could do the black borders).
- I noticed that categories and items are all hardcoded, why is that? I think you should convert it into a "model" of some sort, so when implementing the back end you could just use the model and supplement it with the images urls.
- Are the categories clickable? I couldn't tell. If not, then you should make them clickable but leave the onTap implementation empty.
- You should add general comments on top of your pages, explaining what they do
- From what I understood, you only used FlutterFlow for colouring. I don't really think we need it especially since all the colours will be dynamically changable. It also adds unnecessary files. You could delete it.

2023-02-17 01:40 UTC, skellyhoe commented
I'll take a look at this when changes are made

2023-02-18 19:53 UTC, Digital-Brendan commented
In response to Ali's useful feedback, I refactored pretty much everything after relying on FlutterFlow in the beginning which ended up creating poor code. 

Changes:
- The boxes now take images (though currently use placeholder images until connected to backend - this task was only UI)
- Categories aren't hardcoded. You specify the number of categories (rows) and what image URLs to use, and they are created on screen in a scrollable column
- The categories are now clickable
- Comments have been added where appropriate
- FlutterFlow bloat has been removed

I hope this solves some of the issues that were raised and that the code is now at a satisfactory standard.

Thanks!

2023-02-18 19:54 UTC, Digital-Brendan commented
Also, please note that the errors in the integration testing files aren't my fault (I don't think) :)

2023-02-19 20:38 UTC, AymenBerb reviewed
Hello Brendan, you have pulled the master branch, but haven't added your work coherently to the behaviour of the app. Can you please keep the same main file as in 'master', and add an access to your board from the 'Child board' button in the side menu of the admin board page.

2023-02-21 14:47 UTC, skellyhoe approved these changes
Fixed your .gitignore and removed the files you missed. Looks good

2023-02-21 15:02 UTC, Ali-Alkhars requested changes

2023-02-21 15:02 UTC, Ali-Alkhars commented on lib/pages/child_menu.dart
> +  // const CustomizableColumn({Key? key, required this.rowConfigs}) : super(key: key);
Remove commented out code

2023-02-21 15:02 UTC, Ali-Alkhars commented on lib/pages/child_menu.dart
> +class CustomizableRow extends StatelessWidget {
You can move this class into a separate file in the widgets folder (and all the classes below)

2023-02-21 15:04 UTC, skellyhoe commented
Summary of changes requested by me in the gc:

- Separate customizableRow into smaller widgets.
- CustomizableColumn should return a scaffold instead of a listview.
- Remove generated plugin files.

2023-02-22 15:15 UTC, Digital-Brendan commented
Please find the final version of this UI, thanks.

2023-02-22 20:49 UTC, Ali-Alkhars approved these changes
Well done Brendan! Thanks for doing all the requested changes.

2023-02-22 23:32 UTC, merged