T08 visual timetable UI
AryamanDubey28/seg_coursework_app pull request #7
Opened 2023-02-16 02:54 UTC by skellyhoe

Sprint 1 is finally finished now :)

**Task description:**
Build the page where the admin would set a visual timetable:

- The admin will be presented with the items board
- Each element in the board is a clickable item
- When an image on the items board is clicked, it’s put on a list instead of being highlighted.
- When an image on the timetable is clicked, its popped off the list.
- The visual timetable consists of 5 pictures AT MOST, and is connected with arrows.

**Implemented all of that with the addition of:**

- Timetables can be saved for future use using a button that appears after 2 images are selected.
- A page that shows all saved timetables and allows the admin to delete unwanted timetables.

2023-02-16 12:40 UTC, dmunipi1 approved these changes
Everything looks good, well written clean code with appropriate testing.

Thank you for your work

2023-02-16 12:45 UTC, Ali-Alkhars requested changes
That's some quality work! Thank you.

**Here are some minor stuff to change/add:**
- You should remove commented out code. I have tagged them for you (check the comments below)
- You should add general comments at the top of the pages and widgets files explaining what they do/are used for
- Also comments on top of methods explaining what they do or why they are added

2023-02-16 12:45 UTC, Ali-Alkhars commented on lib/pages/visual_timetable.dart
> +  // List<List<ImageDetails>> listOfTimetables = [];
Remove commented out code

2023-02-16 12:45 UTC, Ali-Alkhars commented on lib/pages/visual_timetable.dart
> +          // if (timetableList.imagesList.length >= 2) buildAddButton(timetableList),
remove here too

2023-02-16 12:45 UTC, Ali-Alkhars commented on lib/widgets/image_square.dart
> +      // padding: const EdgeInsets.all(10),
here too, also line 30

2023-02-16 12:45 UTC, Ali-Alkhars commented on lib/widgets/timetable_row.dart
> +      // color: Colors.amber,
here

2023-02-16 12:45 UTC, Ali-Alkhars commented on test/all_saved_timetables_test.dart
> +// class TestNavigatorObserver extends NavigatorObserver {
here

2023-02-17 01:36 UTC, skellyhoe commented
> That's some quality work! Thank you.
> 
> **Here are some minor stuff to change/add:**
> 
> * You should remove commented out code. I have tagged them for you (check the comments below)
> * You should add general comments at the top of the pages and widgets files explaining what they do/are used for
> * Also comments on top of methods explaining what they do or why they are added

Thank you for your comments and tags. Implemented all!

2023-02-17 03:04 UTC, skellyhoe commented
Just pushed a fix that centers the timetable. Images and arrows now scale depending on screen size. This will make all components of the timetable fit on the screen without scrolling. Hopefully this will be it.

2023-02-17 10:15 UTC, Ali-Alkhars approved these changes
Well done!

2023-02-17 11:30 UTC, merged